# Generated by Django 5.1.2 on 2024-10-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('user', 'Normal User'), ('admin', 'Admin User'), ('technician', 'Technician User')], default='user', max_length=50),
        ),
    ]
