# Generated by Django 5.1.2 on 2024-10-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('user', 'Car Owner'), ('mechanic', 'Mechanic')], default='user', max_length=50),
        ),
    ]
