# Generated by Django 5.1.2 on 2024-10-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicles_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='type',
            field=models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycle')], max_length=20),
        ),
    ]
